### ISSUE TITLE
Isn't working, HTTP Error 403

### ISSUE THREAD

**Issue by ghost** [AladW/youtube-10hourify#2]
I tested it with a random video, to test it, but it didn't work. Console output:
`$ youtube-10hourify https://www.youtube.com/watch?v=WXPHslZvEcA
[youtube] WXPHslZvEcA: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: /tmp/sDNiqxvYK8/Nightcore - Lies - (Lyrics)-WXPHslZvEcA.f299.mp4
[download] 100% of 51.06MiB in 00:07
ERROR: unable to download video data: HTTP Error 403: Forbidden
youtube-10hourify: failed to retrieve video: 256 at /usr/bin/youtube-10hourify line 31.`

**Comment by AladW** [comment]
Does it work with `youtube-dl`?

**Comment by ghost** [comment]
Fixed it with the command `youtube-dl --rm-cache-dir`. 
It is a Problem from youtube-dl cache: 
https://github.com/ytdl-org/youtube-dl/issues/23638
